//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempConverterClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fluidToOunce", ReplyAction="*")]
        float fluidToOunce(float fo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fluidToOunce", ReplyAction="*")]
        System.Threading.Tasks.Task<float> fluidToOunceAsync(float fo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/gillToMill", ReplyAction="*")]
        float gillToMill(float gm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/gillToMill", ReplyAction="*")]
        System.Threading.Tasks.Task<float> gillToMillAsync(float gm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cupToMill", ReplyAction="*")]
        float cupToMill(float cm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cupToMill", ReplyAction="*")]
        System.Threading.Tasks.Task<float> cupToMillAsync(float cm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pintToGill", ReplyAction="*")]
        float pintToGill(float pg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pintToGill", ReplyAction="*")]
        System.Threading.Tasks.Task<float> pintToGillAsync(float pg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pintToFluidOunce", ReplyAction="*")]
        float pintToFluidOunce(float pfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pintToFluidOunce", ReplyAction="*")]
        System.Threading.Tasks.Task<float> pintToFluidOunceAsync(float pfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/quartToMill", ReplyAction="*")]
        float quartToMill(float qm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/quartToMill", ReplyAction="*")]
        System.Threading.Tasks.Task<float> quartToMillAsync(float qm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/gallToQuart", ReplyAction="*")]
        float gallToQuart(float gq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/gallToQuart", ReplyAction="*")]
        System.Threading.Tasks.Task<float> gallToQuartAsync(float gq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/gallToPint", ReplyAction="*")]
        float gallToPint(float gp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/gallToPint", ReplyAction="*")]
        System.Threading.Tasks.Task<float> gallToPintAsync(float gp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BarToLitres", ReplyAction="*")]
        float BarToLitres(float bl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BarToLitres", ReplyAction="*")]
        System.Threading.Tasks.Task<float> BarToLitresAsync(float bl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TempConverterClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TempConverterClient.ServiceReference1.WebService1Soap>, TempConverterClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float fluidToOunce(float fo) {
            return base.Channel.fluidToOunce(fo);
        }
        
        public System.Threading.Tasks.Task<float> fluidToOunceAsync(float fo) {
            return base.Channel.fluidToOunceAsync(fo);
        }
        
        public float gillToMill(float gm) {
            return base.Channel.gillToMill(gm);
        }
        
        public System.Threading.Tasks.Task<float> gillToMillAsync(float gm) {
            return base.Channel.gillToMillAsync(gm);
        }
        
        public float cupToMill(float cm) {
            return base.Channel.cupToMill(cm);
        }
        
        public System.Threading.Tasks.Task<float> cupToMillAsync(float cm) {
            return base.Channel.cupToMillAsync(cm);
        }
        
        public float pintToGill(float pg) {
            return base.Channel.pintToGill(pg);
        }
        
        public System.Threading.Tasks.Task<float> pintToGillAsync(float pg) {
            return base.Channel.pintToGillAsync(pg);
        }
        
        public float pintToFluidOunce(float pfo) {
            return base.Channel.pintToFluidOunce(pfo);
        }
        
        public System.Threading.Tasks.Task<float> pintToFluidOunceAsync(float pfo) {
            return base.Channel.pintToFluidOunceAsync(pfo);
        }
        
        public float quartToMill(float qm) {
            return base.Channel.quartToMill(qm);
        }
        
        public System.Threading.Tasks.Task<float> quartToMillAsync(float qm) {
            return base.Channel.quartToMillAsync(qm);
        }
        
        public float gallToQuart(float gq) {
            return base.Channel.gallToQuart(gq);
        }
        
        public System.Threading.Tasks.Task<float> gallToQuartAsync(float gq) {
            return base.Channel.gallToQuartAsync(gq);
        }
        
        public float gallToPint(float gp) {
            return base.Channel.gallToPint(gp);
        }
        
        public System.Threading.Tasks.Task<float> gallToPintAsync(float gp) {
            return base.Channel.gallToPintAsync(gp);
        }
        
        public float BarToLitres(float bl) {
            return base.Channel.BarToLitres(bl);
        }
        
        public System.Threading.Tasks.Task<float> BarToLitresAsync(float bl) {
            return base.Channel.BarToLitresAsync(bl);
        }
    }
}
